sonar.projectKey=story2code-UserStory-01-qwen-3.5-run2-2026-07-18_run2
sonar.working.directory=/Users/yadanarphyo/Space/ESS/Dissertation/Story2Code/Runs/2026-07-18_run2/UserStory-01_qwen-3.5/run2/src/.sonarqube/out/.sonar
sonar.projectBaseDir=/Users/yadanarphyo/Space/ESS/Dissertation/Story2Code/Runs/2026-07-18_run2/UserStory-01_qwen-3.5/run2/src
sonar.pullrequest.cache.basepath=/Users/yadanarphyo/Space/ESS/Dissertation/Story2Code/Runs/2026-07-18_run2/UserStory-01_qwen-3.5/run2/src

69D09FC9-8B5F-4772-95E7-5E1EC4A2D468.sonar.projectKey=story2code-UserStory-01-qwen-3.5-run2-2026-07-18_run2:69D09FC9-8B5F-4772-95E7-5E1EC4A2D468
69D09FC9-8B5F-4772-95E7-5E1EC4A2D468.sonar.projectName=Implementation
69D09FC9-8B5F-4772-95E7-5E1EC4A2D468.sonar.projectBaseDir=/Users/yadanarphyo/Space/ESS/Dissertation/Story2Code/Runs/2026-07-18_run2/UserStory-01_qwen-3.5/run2/src
69D09FC9-8B5F-4772-95E7-5E1EC4A2D468.sonar.sourceEncoding=utf-8
69D09FC9-8B5F-4772-95E7-5E1EC4A2D468.sonar.tests=
69D09FC9-8B5F-4772-95E7-5E1EC4A2D468.sonar.sources=\
"/Users/yadanarphyo/Space/ESS/Dissertation/Story2Code/Runs/2026-07-18_run2/UserStory-01_qwen-3.5/run2/src/Controllers/RecyclingFacilitiesController.cs",\
"/Users/yadanarphyo/Space/ESS/Dissertation/Story2Code/Runs/2026-07-18_run2/UserStory-01_qwen-3.5/run2/src/Models/RecyclingFacility.cs",\
"/Users/yadanarphyo/Space/ESS/Dissertation/Story2Code/Runs/2026-07-18_run2/UserStory-01_qwen-3.5/run2/src/Program.cs",\
"/Users/yadanarphyo/Space/ESS/Dissertation/Story2Code/Runs/2026-07-18_run2/UserStory-01_qwen-3.5/run2/src/Services/GetNearbyRecyclingFacilitiesService.cs",\
"/Users/yadanarphyo/Space/ESS/Dissertation/Story2Code/Runs/2026-07-18_run2/UserStory-01_qwen-3.5/run2/src/Services/IGetNearbyRecyclingFacilitiesService.cs",\
"/Users/yadanarphyo/Space/ESS/Dissertation/Story2Code/Runs/2026-07-18_run2/UserStory-01_qwen-3.5/run2/src/obj/Release/net8.0/Implementation.GlobalUsings.g.cs",\
"/Users/yadanarphyo/Space/ESS/Dissertation/Story2Code/Runs/2026-07-18_run2/UserStory-01_qwen-3.5/run2/src/obj/Release/net8.0/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs",\
"/Users/yadanarphyo/Space/ESS/Dissertation/Story2Code/Runs/2026-07-18_run2/UserStory-01_qwen-3.5/run2/src/obj/Release/net8.0/Implementation.AssemblyInfo.cs",\
"/Users/yadanarphyo/Space/ESS/Dissertation/Story2Code/Runs/2026-07-18_run2/UserStory-01_qwen-3.5/run2/src/appsettings.Development.json",\
"/Users/yadanarphyo/Space/ESS/Dissertation/Story2Code/Runs/2026-07-18_run2/UserStory-01_qwen-3.5/run2/src/appsettings.json",\
"/Users/yadanarphyo/Space/ESS/Dissertation/Story2Code/Runs/2026-07-18_run2/UserStory-01_qwen-3.5/run2/src/obj/Implementation.csproj.nuget.dgspec.json",\
"/Users/yadanarphyo/Space/ESS/Dissertation/Story2Code/Runs/2026-07-18_run2/UserStory-01_qwen-3.5/run2/src/obj/project.assets.json",\
"/Users/yadanarphyo/Space/ESS/Dissertation/Story2Code/Runs/2026-07-18_run2/UserStory-01_qwen-3.5/run2/src/obj/Release/net8.0/staticwebassets.build.json",\
"/Users/yadanarphyo/Space/ESS/Dissertation/Story2Code/Runs/2026-07-18_run2/UserStory-01_qwen-3.5/run2/src/obj/Debug/net8.0/staticwebassets.build.json",\
"/Users/yadanarphyo/Space/ESS/Dissertation/Story2Code/Runs/2026-07-18_run2/UserStory-01_qwen-3.5/run2/src/bin/Release/net8.0/Implementation.deps.json",\
"/Users/yadanarphyo/Space/ESS/Dissertation/Story2Code/Runs/2026-07-18_run2/UserStory-01_qwen-3.5/run2/src/bin/Release/net8.0/appsettings.json",\
"/Users/yadanarphyo/Space/ESS/Dissertation/Story2Code/Runs/2026-07-18_run2/UserStory-01_qwen-3.5/run2/src/bin/Release/net8.0/appsettings.Development.json",\
"/Users/yadanarphyo/Space/ESS/Dissertation/Story2Code/Runs/2026-07-18_run2/UserStory-01_qwen-3.5/run2/src/bin/Release/net8.0/Implementation.runtimeconfig.json",\
"/Users/yadanarphyo/Space/ESS/Dissertation/Story2Code/Runs/2026-07-18_run2/UserStory-01_qwen-3.5/run2/src/bin/Debug/net8.0/Implementation.deps.json",\
"/Users/yadanarphyo/Space/ESS/Dissertation/Story2Code/Runs/2026-07-18_run2/UserStory-01_qwen-3.5/run2/src/bin/Debug/net8.0/appsettings.json",\
"/Users/yadanarphyo/Space/ESS/Dissertation/Story2Code/Runs/2026-07-18_run2/UserStory-01_qwen-3.5/run2/src/bin/Debug/net8.0/appsettings.Development.json",\
"/Users/yadanarphyo/Space/ESS/Dissertation/Story2Code/Runs/2026-07-18_run2/UserStory-01_qwen-3.5/run2/src/bin/Debug/net8.0/Implementation.runtimeconfig.json"

69D09FC9-8B5F-4772-95E7-5E1EC4A2D468.sonar.cs.analyzer.projectOutPaths=\
"/Users/yadanarphyo/Space/ESS/Dissertation/Story2Code/Runs/2026-07-18_run2/UserStory-01_qwen-3.5/run2/src/.sonarqube/out/0"
69D09FC9-8B5F-4772-95E7-5E1EC4A2D468.sonar.cs.roslyn.reportFilePaths=\
"/Users/yadanarphyo/Space/ESS/Dissertation/Story2Code/Runs/2026-07-18_run2/UserStory-01_qwen-3.5/run2/src/.sonarqube/out/0/Issues.json"
69D09FC9-8B5F-4772-95E7-5E1EC4A2D468.sonar.cs.scanner.telemetry=\
"/Users/yadanarphyo/Space/ESS/Dissertation/Story2Code/Runs/2026-07-18_run2/UserStory-01_qwen-3.5/run2/src/.sonarqube/out/0/Telemetry.json"

69D09FC9-8B5F-4772-95E7-5E1EC4A2D468.sonar.working.directory=/Users/yadanarphyo/Space/ESS/Dissertation/Story2Code/Runs/2026-07-18_run2/UserStory-01_qwen-3.5/run2/src/.sonarqube/out/.sonar/mod0
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=69D09FC9-8B5F-4772-95E7-5E1EC4A2D468

